### ISSUE TITLE
Tools/CSV_generator

### ISSUE THREAD

**Issue by Huxiiiao** [Davide-Zamboni/CSI_Complete_Guide#2]
I want to know how to use this tool,can you give me some suggestions

**Comment by Huxiiiao** [comment]
make can not find this file pcap/pcap.h

**Comment by Davide-Zamboni** [comment]
Hi, simply with `tcpdump` you have to generate a pcap on an external USB drive. Then on your pc you specify the filename  (`line 110`), and set the BW constant (`line 8`).  The make can not find the `pcap.h` because you have to install the library. If you have homebrew run `brew install libpcap`
