### ISSUE TITLE
About Tools CSV_Generator Makefile

### ISSUE THREAD

**Issue by Huxiiiao** [Davide-Zamboni/CSI_Complete_Guide#3]
cpp file has some errors,I can not solve them

**Comment by Davide-Zamboni** [comment]
Usually is because you have set some parameters wrong. Please be more specific or perform the steps of the other issue

**Comment by Huxiiiao** [comment]
Thank you for your reply, thank you very much.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Davide-Zamboni/CSI_Complete_Guide"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月11日(星期六) 晚上11:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Davide-Zamboni/CSI_Complete_Guide] About Tools CSV_Generator Makefile (Issue #3)





 
Usually is because you have set some parameters wrong. Please be more specific or perform the steps of the other issue
